import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Arvae Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600;1,700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className="flex flex-col justify-center items-center m-4 min-h-screen font-playfair">
        <div className="">
          <div className="relative w-32 h-44 rounded-md border">
            <Image
              className="rounded-md"
              src={"/arvae.JPG"}
              alt="no image sorry"
              objectFit="cover"
              layout="fill"
            />
          </div>
        </div>
        <div>
          <p className="font-sourceSans">Hello there! I am</p>
          <h1 className="text-lg font-bold">Franz Arvae Ignacio</h1>
        </div>
      </main>
    </>
  )
}

export default Home
